# -*- coding: utf-8 -*-
"""perulangan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-gsvLXGvyNrN0c_kN2MPxsUU5yAuDyvo
"""

print("======hai teman======")
print("ini adalah Perulangan")
n = int(input("masukan nilai yang ingin di ketahui : "))
x = 0
while (x < n):
  if (10 ** x > n):
     break
  else:
     print("kita hitung nilai terkecil dari 10^x")
  x += 1

print("Nilai terkecil dari 10^ x lebih dari n adalah", 10 ** x)
print("=====terima kasih=====")